# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform restic installation tasks
  when: restic_enabled | bool
  tags:
    - setup-all
    - setup-restic
    - install-all
    - install-restic
  block:
    - name: Validate restic configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install restic
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform restic command execution tasks
  when: restic_enabled | bool
  tags:
    - command-restic
  block:
    - name: Run restic command
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/command.yml"

- name: Perform restic uninstallation tasks
  when: not restic_enabled | bool
  tags:
    - setup-all
    - setup-restic
  block:
    - name: Uninstall restic
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
